name: image-lora-prep
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pillow>=10
  - numpy>=1.24
  - click>=8.1
  - piexif>=1.1
  - tk
  - requests>=2.31
  - pillow-avif-plugin>=1.4
  - openai>=1.40
